{% set name = "vae" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/labsyspharm/vae.git
  git_tag: v{{ version }}
  # git_rev: main

build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - vae=vae.scripts.__main__:main

requirements:
  host:
    - pip
    - python >=3.11,<3.12
    - poetry-core >=1.0.0

  run:
    - python >=3.11,<3.12

    # Zarr2 stack
    - zarr <=2.14.0
    - numcodecs <0.13
    - cellcutter =0.2.7

    # UMAP/scikit-learn compatibility
    - setuptools <81
    - umap-learn <0.5.4
    - scikit-learn <1.3

    # image processing
    - tifffile =2024.12.12
    - scikit-image
    - opencv

    # data handling
    - natsort
    - pandas
    - pyarrow
    - pyyaml
    - dask
    - ome-types

    # deep learning
    - keras
    - tensorflow =2.15.0 
    # this is the critical dependency: the pipeline currently requires TensorFlow 2.15.
    # Newer versions (>=2.16) cause compatibility issues with imports such 
    # as from tensorflow.keras import ...", and 2.15 is compatible with the
    # available o2 GPU/CUDA modules.
    - tensorflow-probability =0.23.0
    - pytorch
    - pytorch-lightning
    - segmentation-models-pytorch

    # viz/analysis
    - napari
    - seaborn

    # Leiden community detection
    - scanpy
    - igraph
    - leidenalg

test:
  imports:
    - vae

about:
  home: https://github.com/labsyspharm/vae
  license: MIT
  license_family: MIT
  description:
    MORPHAEUS (VAE) is a pipeline for generating cropped image patches from multi-channel
    TIF images, training a variational autoencoder, encoding image patches
    into a latent space, and performing Leiden community detection.
