{% set name = "morphaeus" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # git_url: https://github.com/gjbaker/vae.git
  #git_url: https://github.com/labsyspharm/vae
  git_url: git@github.com:labsyspharm/vae.git  # labsyspharm/vae uses ssh
  git_rev: main
build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
    - "{{ PYTHON }} -m pip install git+https://github.com/catalystneuro/lazy_ops.git@master -vv "
  entry_points:
    - vae=vae.scripts.__main__:main
  noarch: python

requirements:
  build:
    - poetry
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - zarr
    - hdbscan
    - umap-learn
    - keras
    - natsort
    - pandas
    - pyarrow
    - pyyaml
    - seaborn
    - tensorflow=2.15.0  # avoiding "from tensorflow.keras import XX" errors with tf >= 2.16 and making compatible with available o2 GPU CUDA modules.
    - cellcutter
    - opencv
    - dask

test:
  imports:
    - vae

about:
  home: https://github.com/labsyspharm/vae
  license: MIT
  license_family: BSD
  summary: "Generate cropped image patches from a multi-channel TIF image, train a VAE model, and perform clustering on latent space image patch encodings."
  description-file: README.md

extra:
  recipe-maintainers:
    - Gregory J. Baker <gregory_baker2@hms.harvard.edu>
