{% set name = "vae" %}
{% set version = "0.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/labsyspharm/vae.git
  git_rev: main
  # git_tag: v0.0.5
build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
    - "{{ PYTHON }} -m pip install git+https://github.com/catalystneuro/lazy_ops.git@master -vv "
    - "{{ PYTHON }} -m pip install git+https://github.com/labsyspharm/cellcutter.git@main -vv "
  entry_points:
    - vae=vae.scripts.__main__:main
  noarch: python

requirements:
  build:
    - python
    - pip
    - setuptools
    - wheel
  host:
    - python
    - pip
    - "poetry-core>=1.4,<1.7"  # import os bug in recent version of poetry-core
  run:
    - python<3.14
    - hdbscan
    - umap-learn
    - keras
    - natsort
    - pandas
    - pyarrow
    - pyyaml
    - seaborn
    - tifffile
    - scikit-learn<1.3
    - scikit-image
    - tensorflow=2.15.0  # avoiding "from tensorflow.keras import XX" errors with tf >= 2.16 and making compatible with available o2 GPU CUDA modules.
    - tensorflow-probability=0.23.0  # compatible with TF 2.15.0
    - zarr<3.0.0
    - opencv
    - napari
    - dask
    - ome-types
    - pytorch # used for Pytorch segmentation models 
    - pytorch-lightning
    - segmentation-models-pytorch

test:
  imports:
    - vae

about:
  home: https://github.com/labsyspharm/vae
  license: MIT
  license_family: BSD
  summary: "Generate cropped image patches from a multi-channel TIF image, train a VAE model, and perform clustering on latent space image patch encodings."
  description-file: README.md

extra:
  recipe-maintainers:
    - Gregory J. Baker <gregory_baker2@hms.harvard.edu>
