[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "vae"
version = "0.0.3"
description = "Generate cropped image patches from a multi-channel TIF image, train a VAE model, and perform clustering on latent space image patch encodings."
readme = "README.md"
license = "MIT"
keywords =['spatial proteomics, variational autoencoder (VAE), artificial intelligence, tissue phenotyping']
classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: End Users/Desktop',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Topic :: Scientific/Engineering :: Visualization'
]
authors = ["Gregory J. Baker <gregory_baker2@hms.harvard.edu>"]
homepage = "https://github.com/labsyspharm/vae"

[tool.poetry.dependencies]
hdbscan = "*"
umap-learn = "*"
keras = "*"
natsort = "*"
pandas = "*"
pyarrow = "*"
pyyaml = "*"
seaborn = "*"
tensorflow = "2.15.0"
tensorflow-probability = "0.23.0"
zarr = "<3.0.0"
cellcutter = "*"
opencv-python = "*"
dask = "*"

[tool.poetry.scripts]
vae = "vae.scripts.__main__:main"
